apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-service
  namespace: smart-inventory
  labels:
    app: inventory-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: inventory-service
  template:
    metadata:
      labels:
        app: inventory-service
    spec:
      containers:
      - name: inventory-service
        image: gcr.io/PROJECT_ID/inventory-service:latest
        ports:
        - containerPort: 8001
        env:
        - name: DB_URL
          value: "mysql+pymysql://inventory_user:inventory_pass123@mysql-service:3306/smart_inventory"
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: smart-inventory-config
              key: REDIS_HOST
        - name: REDIS_PORT
          valueFrom:
            configMapKeyRef:
              name: smart-inventory-config
              key: REDIS_PORT
        - name: INVENTORY_PORT
          valueFrom:
            configMapKeyRef:
              name: smart-inventory-config
              key: INVENTORY_PORT
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /api/healthz
            port: 8001
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/healthz
            port: 8001
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: inventory-service
  namespace: smart-inventory
spec:
  selector:
    app: inventory-service
  ports:
  - port: 8001
    targetPort: 8001
  type: ClusterIP