apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: smart-inventory
  labels:
    app: order-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
      - name: order-service
        image: gcr.io/PROJECT_ID/order-service:latest
        ports:
        - containerPort: 8002
        env:
        - name: DB_URL
          value: "mysql+pymysql://inventory_user:inventory_pass123@mysql-service:3306/smart_inventory"
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: smart-inventory-config
              key: REDIS_HOST
        - name: REDIS_PORT
          valueFrom:
            configMapKeyRef:
              name: smart-inventory-config
              key: REDIS_PORT
        - name: ORDER_PORT
          valueFrom:
            configMapKeyRef:
              name: smart-inventory-config
              key: ORDER_PORT
        - name: INVENTORY_SERVICE_URL
          value: "http://inventory-service:8001"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /api/healthz
            port: 8002
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/healthz
            port: 8002
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: smart-inventory
spec:
  selector:
    app: order-service
  ports:
  - port: 8002
    targetPort: 8002
  type: ClusterIP