-- 更新 orders 表以支援完整的工作流程
ALTER TABLE orders 
ADD COLUMN customer_name VARCHAR(255) NULL,
ADD COLUMN customer_email VARCHAR(255) NULL,
ADD COLUMN shipping_address TEXT NULL,
ADD COLUMN notes TEXT NULL,
ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
ADD COLUMN paid_at TIMESTAMP NULL,
ADD COLUMN shipped_at TIMESTAMP NULL;


